### PR TITLE
Image Updates

### PR DESCRIPTION
**Pull request by kingy444**
I have incorporated changes from pull https://github.com/MediaBrowser/Emby.Resources/pull/170 so it should be able to be closed once this is merged.

This merge should include some new studio images from pull 170 and ratio corrections on some other items. All should be 1066x600 now.

Not sure what has happened to identify so many deletions, but as you can see they are the same image being uploaded again

### CODE REVIEW

**Comment by LukePulverenti** [comment]
I still would prefer not to merge it in like this. You would have to redo the pull request so that it is only showing files that have actually changed. Thanks.

**Comment by kingy444** [comment]
I tried to revert to the master from mediabrowser repo and just copy the changes over but it still seems to think the files have changed - any suggestions?

**Comment by kingy444** [comment]
re-downloading the files from here seems to have fixed the issues with trying to replace the genre images - just updates to all the studio images now

**Comment by kingy444** [comment]
@LukePulverenti this should be ok to merge now

**Comment by kingy444** [comment]
@LukePulverenti is there anything wrong with this merge still you need me to fix?

**Pull request merged**
